services:
  ppid_laravel_franken:
    container_name: ppid_laravel_franken
    image: ppid_laravel_franken
    build: .
    ports:
      - "8001:80"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: ppid_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ppid_db
      MYSQL_ROOT_PASSWORD: ppiditera12345
      MYSQL_USER: ppid_itera
      MYSQL_PASSWORD: ppiditera12345
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
